version: '3'

services:

# mysql Server
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./seed-data/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rhbbank
      - MYSQL_PASSWORD=rhbbank.dba
      - MYSQL_USER=rhbbank
      - MYSQL_DATABASE=movie

# backend-assessment service
  backend-assessment:
    build:
      context: ./backend-assessment
    volumes:
      - ./configuration:/opt/configuration
    ports:
      - 8080:8080


